default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: [ "default", "low_priority" ]
      threads: 5
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 2) %>
      polling_interval: 0.1

development:
  <<: *default
  workers:
    - queues: "*"
      threads: 3
      processes: 1

test:
  <<: *default
  workers:
    - queues: "*"
      threads: 1
      processes: 1

production:
  <<: *default
  workers:
    - queues: [ "default" ]
      threads: 10
      processes: <%= ENV.fetch("WEB_CONCURRENCY", 3) %>
    - queues: [ "low_priority" ]
      threads: 5
      processes: 1
